source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

target 'OwnTracks' do
platform :ios, '14.0'
pod 'CocoaLumberjack'
pod 'ABStaticTableViewController', :git => 'https://github.com/ckrey/ABStaticTableViewController.git'
pod 'mqttc/MinL', :git => 'https://github.com/ckrey/mqttc.git'

#pod 'libsodium', '~> 1.0'
pod 'libsodium'
pod 'DSJSONSchemaValidation'
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '13.0'
      xcconfig_path = config.base_configuration_reference.real_path
      xcconfig = File.read(xcconfig_path)
      xcconfig_mod = xcconfig.gsub(/DT_TOOLCHAIN_DIR/, "TOOLCHAIN_DIR")
      File.open(xcconfig_path, "w") { |file| file << xcconfig_mod }
    end
  end
end

